### ISSUE TITLE
Any chance to update it to the new version?

### ISSUE THREAD

**Issue by stefan-wiesner** [fred41/tbbmalloc_arma#4]
Hi and first of all thanks for the performance gain with your tbbmalloc.
I just saw that BI updated TBB in dev branch. Any chance to get it also patched from you?

Tweaked: TBB4 updated to version 4.3u6

**Comment by fred41** [comment]
... i don't plan to develop for arma again in the near future.

But since the source code of my allocator modifications (large page support for windows) is available as source code in my repository, everybody familiar with c++ should be able to integrate it in every newer build.

Greets,
Fred41
